cli.go
doc.go

This PR improves the godoc formatting. godoc doesn't support markdown, so that has been removed. More bonuses are that the first line in the package documentation is no longer a license description, so it appears as something reasonable in package listings. Compare:
[old godoc](http://godoc.org/github.com/hooklift/gowsdl)
[new godoc](http://godoc.org/github.com/mjibson/gowsdl)

Improve godoc formatting

---

generator/soap.go

Using the SoapClient in parallel is exhausting the system with the "too many open files" error due to not closing the request socket after downloading the response.
This patch includes the flag "Close" on the Request object so that it sends the "connection: close" header and close the socket after reading the response.

Set Request Close flag to set connection: close header

---

common.mk

Looks like `make build` was broken by 13eb19f4e5612f4ab08b077b51d4f63b21f8ef7d. This fixed it for me.

Fix `make build`

---

soap_tmpl.go

I'm opening this PR to get some feedback since I'm very new at writing Go code.
These changes allow unmarshalling and marshalling to happen in a single pass, which allows a broader range of SOAP responses to be parsed. In particular, it handles the case where the `xmlns` used on the `<SOAP-ENV:Body>` entries is declared on a parent element instead of on the entry itself.
I would have liked to add some tests here, but I'm not clear on how to structure tests that use the generated code from `soap_tmpl.go`. I'm happy to add some tests if someone can give me some pointers on how to do so. I was able to run `make test`, so I at least don't think I broke any of the existing tests.
Fixes #37

Implement xml.Unmarshaller for SOAPBody

---

soap_tmpl.go

These changes were proposed for the generated output file over at https://github.com/appropriate/go-virtualboxclient/pull/1 and I thought they seemed reasonable.
Please take a look! :+1:

Add additional err handling to SOAP template

---

gowsdl.go
types_tmpl.go

I found gowsdl doesn't handle element's ref attribute like following:
```xml
<xs:element name="SearchBinSet">
<xs:complexType>
<xs:sequence>
<xs:element ref="tns:Bin" minOccurs="0" maxOccurs="unbounded"/>
</xs:sequence>
<xs:attribute name="NarrowBy" type="xs:string" use="required"/>
</xs:complexType>
</xs:element>
```
source: http://webservices.amazon.com/AWSECommerceService/AWSECommerceService.wsdl?rw_useCurrentProtocol=1
Gowsdl results a empty inline struct without name which cannot be compiled.
I modified types_tmpl.go to support this, after modification, it will generate code:
```go
type SearchBinSet struct {
XMLName  xml.Name `xml:"http://webservices.amazon.com/AWSECommerceService/2013-08-01 SearchBinSet"`
Bin      []*Bin `xml:"Bin,omitempty"`
NarrowBy string …
```

Support for element type ref attribute

---

cmd/gowsdl/main.go
gowsdl.go
gowsdl_test.go

We're using a Wsdl which has types similar in name but differing in capitalisation. 
At the moment gowsdl just makes all generated structs public by default which leads to "broken" (a.k.a. not compiling) Go files in our case.
I added the possibility to make the export of types optional. I remained the default to true so no current user should be affected when upgrading.

Make export of generated structs optional

---

gowsdl_test.go
operations_tmpl.go
soap_tmpl.go

In order to allow the SOAPClient to send a
SOAPHeader without modification of generated code,
a new method SetHeader was added to both the
SOAPClient and to the generated operation.
The header, once set, is preserved between
invocations of other methods in the same instance.
This allows client code to call SetHeader()
with the desired header, including nil to remove
it from future calls in the same instance.
The SOAPHeader usually holds authentication info,
and we can benefit from reusing already set
credentials between invocations.
Please review and let me know if this could be merged upstream.
I don't know if it is possible for someone to test out this change
by generating client code to communicate with remote services,
and verify it is working as intended. I can confirm from logs
that …

Allow clients to add SOAPHeader in SOAPClient.

---

gowsdl.go
types_tmpl.go

Recently we added the possibility to leave the defined types as they were defined in the wsdl, i.e. not making them public altogether. This can be switched on (in this case switched off) by a command line flag called `make-public` which defaults to true. The feature was introduced in #56 . 
This resolved some unwanted conflicts in some WSDLs, where there were different types with the same name only differentiated by capitalization.
I recently experienced that it also introduced another unwanted behaviour, i.e. fields within the types are also downcase/unexported which leads to broken Marshaling/Unmarshaling of XML.
This PR retains the ability to marshal the generated types, because only
exported fields are marshaled/unmarshaled by encoding/xml.

Always export fields of structs

---

gowsdl.go
gowsdl_test.go
types_tmpl.go

Previously this was using the same string as the variable name and the string value. Additionally underscores were not preserved in the var name - as they are valid in a go identifier I figure they probably should be.

Don't mangle enumeration strings

---

header_tmpl.go
operations_tmpl.go
soap_tmpl.go

New structs WSSSecurityHeader, WSSUsernameToken and its child structs WSSUsername and WSSPassword. XML namespace problems are dealt with by using vania-pooh's workaround:  https://github.com/golang/go/issues/9519#issuecomment-252196382
Convenience function `NewWSSSecurityHeader` to ease header creation (the header is not automatically added to the SOAP client).
`SetHeader` method is kept for compatibility. There is a new `AddHeader` method to add headers to the SOAP call. There is now support for several headers instead of only one.
Cosmetic changes in header_tmpl.go to sort import names alphabetically.
Sample code:
> // "1" is for 'mustUnderstand' attribute; empty if not specified
> hdr := myservice.NewWSSSecurityHeader("sampleuser", "samplepassword", "1")
> …

Added basic support for WSS Security header

---

gowsdl.go

Re: #81 
After this change the includes for the ONVIF specification are downloaded properly, and 404 error are properly surfaced.

Have includes download from same namespace where they were included

---

cmd/gowsdl/main.go

It's confusing to get a poop emoji as a result when the generation was successful.

Replace poop emoji with thumbs up

---

gowsdl.go

According to [XSD spec](https://www.w3.org/TR/xmlschema11-1/#schema-loc) there is no difference between dereferencing `schemaLocation` in `xsd:include` and `xsd:import`.
> When schema location values (i.e. `schemaLocation` attributes on `<include>`, `<redefine>`, `<override>`, and `<import>` in schema documents, or `xsi:schemaLocation` and `xsi:noNamespaceSchemaLocation` attributes in instance documents) are dereferenced and the values are relative references, then the [base URI] of the [owner element] must be used to resolve the relative references.

Fix dereference of schemaLocation attribute on <include>

---

fixtures/test.wsdl
gowsdl_test.go
types_tmpl.go
xsd.go

gowsdl for XSD:
```
<s:element name="GetInfo">
<s:complexType>
<s:sequence>
<s:element name="Id">
<s:annotation>
<s:documentation>comment</s:documentation>
</s:annotation>
<s:simpleType>
<s:restriction base="s:string">
<s:minLength value="2"/>
</s:restriction>
</s:simpleType>
</s:element>
</s:sequence>
</s:complexType>
</s:element>
```
generates next code, where `Id` is an empty struct:
```
type GetInfo struct {
XMLName	xml.Name	`xml:"http://www.mnb.hu/webservices/ GetInfo"`
Id	struct {
}	`xml:"Id,omitempty"`
} 
```
With this pull request it will generate it as:
```
type GetInfo struct {
XMLName	xml.Name	`xml:"http://www.mnb.hu/webservices/ GetInfo"`
Id	string	`xml:"Id,omitempty"`
}
```

Fix complex type with simple type

---

gowsdl.go

Before:
```
$ gowsdl https://www.onvif.org/onvif/ver10/device/wsdl/devicemgmt.wsdl
🍀  Downloading file https://www.onvif.org/onvif/ver10/device/wsdl/devicemgmt.wsdl
🍀  Downloading external schema location https://www.onvif.org/onvif/ver10/schema/onvif.xsd
🍀  Downloading external schema location http://www.w3.org/2005/05/xmlmime
🍀  Downloading external schema location http://www.w3.org/2003/05/soap-envelope
🍀  Downloading external schema location http://docs.oasis-open.org/wsn/b-2.xsd
🍀  Downloading external schema location http://www.w3.org/2004/08/xop/include
🍀  Downloading external schema location https://www.onvif.org/onvif/ver10/device/wsdl/common.xsd
🍀  Received response code 404
```
After:
```
$ gowsdl https://www.onvif.org/onvif/ver10/device/wsdl/devicemgmt.wsdl
🍀  Downloading file …
```

Fix schemaLocation dereferencing of relative path

---

example/example.go
example/gen/gen.go
gowsdl.go
gowsdl_test.go
header_tmpl.go
operations_tmpl.go
soap/soap.go
soap/soap_test.go

* Move soap client proxy to separate package `soap`.
* Generate interfaces for generated services.
closes https://github.com/hooklift/gowsdl/issues/106

Refactor soap client

---

soap/soap.go
wsdl.go

The way it is implemented now, all headers will always be wrapped in a <Items> tag.
```
<Header>
<Items>
<Any headers are added here>
</Items>
</Header>
```
Now headers are added correctly inside the top level <Header> tag
```
<Header>
<Any headers are added here>
</Header>
```

Headers are no longer wrapped in a <Items> tag

---

soap/soap.go

Options extended to provide various timeout parameters
Defaults specified for various timeouts
Explicit options can be specified with the new api cals

added fixes related to soap http timeout

---

soap/soap.go

This allows overriding both transport (RoundTripper) configuration
and anything else related to the client. Including using a completely
separate client.
Attempts to resolve https://github.com/hooklift/gowsdl/issues/125

Added WithHTTPClient option

---

gowsdl.go

If a xsd file imports other xsd files, it was not processing them. Only
includes were processed correctly, this commit will also recursively
read and process import statements.

Read imports from xsd files as well

---

types_tmpl.go

Adapt simple type template to support generation of slices.
I.e., generate a slice if an item type is given.

support generating arrays of simple types

---

gowsdl.go

Imports/includes were processed more than once, because the map of already processed imports was filled too late.

fix import recursion to prevent duplicate imports

---

operations_tmpl.go

For operations with an empty soap action the client would omit the soap action field entirely which would make the request invalid with some APIs.
Adding an explicit empty string to the request seems to resolve that issue

force empty soap action to exist in the generated request

---

soap/soap.go

From the docs on `request.WithContext`:
> WithContext returns a shallow copy of r with its context changed to ctx.
Currently, return value from `req.WithContext` is not used which means once they are issued, they cannot be canceled.

Fix setting context on request

---

soap/soap.go

SOAP headers were not wrapped in `<Header></Header>` tags and were
instead marshaled directly into the `<Envelope>` tag.
I encountered this problem while trying to use `wss := soap.NewWSSSecurityHeader(...)` followed by `client.AddHeader(wss)`.  
Before this fix, the `<Security>` tags were marshaled directly inside the `<Envelope>` tag, not within a `<Header>` tag as expected.
Very similar to the patch suggested in #147 but allows for the header element to be ignored by the marshaller if no headers have been added.
fixes #147

fix incorrect marshalling of SOAP headers

---

soap/soap.go

This PR adds support to explicitly set all headers, overwriting any previously set headers.
Currently, the client only allows adding headers - which means that it cannot be reused for requests that need different headers, and a new instance must be created for every such request.

Allow setting all headers explicitly

---

cmd/gowsdl/main.go

Hi. I want to add `-dir` option for specifying path for package directory will be created.
so after that, we can execute `go run ./cmd/gowsdl/main.go -p gen -o gen.go -d example ./fixtures/stock.wsdl`

Dir option

---

.gitignore
go.mod
go.sum
soap/soap.go
soap/soap_test.go

https://github.com/hooklift/gowsdl/issues/180
This PR fixes the described discrepancy between [SOAP 1.1 spec](https://www.w3.org/TR/2000/NOTE-SOAP-20000508/#_Ref477795996) and gowsdl implementation of fault detail.
Add a new function 
```
func (s *Client) 
CallWithFault(soapAction string, request, response, faultDetail interface{}) error
```
which allows to inject a custom fault detail type, similar to request and response.
Previously existing `Call` function remain backwards compatible and passes in `nil` for the fault, which is correctly handled (ignores detail information).
A slight awkwardness with this approach is: you cannot simply rely on Body.Fault == nil as a condition indicating there is no fault, since Fault is initialized with the custom detail type. Instead, there's a boolean …

Custom SOAPFault detail unmarshaling

---

types_tmpl.go
xsd.go

Fixes #161 
In these cases the complex-type extension consists of a choice-set. These are not generated correctly so added the choice element template generation and choice type in the structure.

Implemented choices inside complex type extensions

---

gowsdl.go
types_tmpl.go

Hi,
Thanks for this gowsdl project, it helped a lot in our project. This is our 2 cents in supporting nillable=true attribute of WSDL, so that nillable fields can be identified in SOAP request and response, especially for fields of integer data types(int, int32, etc...).
We tried to read the gowsdl code generator design, and if we misunderstood anything, please don't hesitate to let us know, and we can update our code to make them right.
Thanks and regards

add nillable=true support for data fields

---

types_tmpl.go

There is an error in handling XSDAttribute type. I have fixed it and now running go test shows "all passed":
```
...
Reading file /proj/work/huangnan/gitrepos/gowsdl/fixtures/epcis/BusinessScope.xsd
Reading file /proj/work/huangnan/gitrepos/gowsdl/fixtures/epcis/EPCglobal-epcis-query-1_2.xsd
PASS
ok      github.com/hooklift/gowsdl      1.504s
```

fix wrong Nillable field on XSDAttribute

---

soap/soap.go
soap/soap_test.go

Same as #140, this adds the ability to get the HTTP status code returned from the server if the request fails.  
It appears tests in soap/soap_test.go were broken due to invalid struct names.  I fixed those as well in this PR so I could add tests for RequestError

Pass HTTP status code to client if request fails

---

Makefile
soap/MMAEncoder.go
soap/MTOMEncoder.go
soap/soap.go
soap/soap_test.go

This PR introduces support for SOAP messages with attachments as multipart files using MTOM (https://www.w3.org/TR/soap12-mtom/)

With this PR gowsdl will be enabled to support SOAP MTOM

---

fixtures/epcis/epcisquery.src
fixtures/workday-time-min.wsdl
gowsdl_test.go
types_tmpl.go

I decided to revisit #204, which I filed earlier this year.  The problem is that #166 add added [this special case in the `ComplexTypesGlobal` template](https://github.com/hooklift/gowsdl/blob/9e1cc9a7689230f4da66504844af631a0c4767cc/types_tmpl.go#L146-L148), which causes all `string`-extending `complexType`s to generate a `string` type alias.
I fully admit ignorance as to the specific reasons behind this behavior.  My fix is to change the template so it generates the string alias if the underlying type is `string` *and* there are no additional `xsd:attribute` elements.  This appears to fix my case while preserving whatever optimization the special case was for.
Making the change caused `TestEPCISWSDL` to fail, because `PartnerIdentification` in `Partner.xsd` is a `string`-extending …

Correctly generate `complexType`s which extend `string`.

---

fixtures/epcis/epcisquery.src
gowsdl.go
gowsdl_test.go
types_tmpl.go

Go’s `encoding/xml` handling of namespaces is deeply broken.  In particular, it can’t marshal XML using namespace prefixes, ala:
```xml
<document xmlns:ns="whatever">
<ns:node ns:type="foo">…</ns:node>
</document>
```
Only by setting the default namespace, ala:
```xml
<document xmlns="whatever">
<node type="foo">…</node>
</document>
```
This is broken.  Per [the XML Specification](https://www.w3.org/TR/xml-names/#dt-defaultNS), default namespaces don’t affect attributes; they **MUST** have a prefix:
> The namespace name for an unprefixed attribute name always has no value.
This causes any attributes in WSDL requests to end up in the wrong namespace, which makes them fail validation & return a SOAP fault.
The only way to get attributes into the correct namespace is to include the namespace …

Work around buggy encloding/xml ns attribute marshalling

---

fixtures/test.wsdl
gowsdl_test.go
types_tmpl.go

For instance, this XSD definition:
```xsd
<xs:element name="myType">
<xs:simpleType>
<xs:restriction base="xs:string">
<xs:minLength value="1"/>
</xs:restriction>
</xs:simpleType>
</xs:element>
```
shall result in this generated type definition:
```go
type myType string
```
The implementation approach is identical to the already existing support for local complex types. It basically copies the "SimpleType" template into the element processing when no Type is defined for the element.
A simple test with an enumeration has also been implemented

Support local simple types inside elements

---

types_tmpl.go
xsd.go

```xsd
<xs:complexType name="myComplexType">
<xs:complexContent>
<xs:extension base="myBaseType">
<xs:sequence>
<xs:choice>
<xs:element name="myType" type="xs:string"/>
</xs:choice>
</xs:sequence>
</xs:extension>
</xs:complexContent>
</xs:complexType>
```
must result in a struct field `MyType` of type `string`.

Type generation: support extension>sequence>choice elements

---

fixtures/test.wsdl
gowsdl_test.go
types_tmpl.go

Note that this pull request is based on top of #220 (first two commit) because it also proposes a cleanup of variable names and usage across the entire types template (final commit).
The interface methods must be generated for generated types with underlying type `soap.XSDDateTime`, `soap.XSDDate` and `soap.XSDTime`, such that they can be referenced
```xsd
<xs:complexType name="myComplexType">
<xs:sequence>
<xs:element ref="myType"/>                      
</xs:sequence>
</xs:complexType>
<xs:element name="myType" type="xs:dateTime"/>
```
as opposed to direct type declaration:
```xsd
<xs:complexType name="myComplexType">
<xs:sequence>
<xs:element name="myType" type="xs:dateTime"/>  
</xs:sequence>
</xs:complexType>
```
Calls are redirected to `soap.XSDDateTime.MarshalXML()` and …

Generate xml.Marshaler and xml.Unmarshaler interface implementations for date/time types

---

fixtures/test.wsdl
gowsdl_test.go
types_tmpl.go

Note that this pull request is based on top of #220 (first two commit) #222 (following three commits) because it also needs to modify what has been introduced in those PRs.
Simple types with "restriction base" and "list itemType" were defined with pointer types, if they did not resolve to basic Go types.
This example definitions:
```xsd
<xs:simpleType name="MyType">
<xs:restriction base="myBaseType"/>
</xs:simpleType>
<xs:simpleType name="myBaseType">
<xs:restriction base="xs:int">
<xs:totalDigits value="3"/>
</xs:restriction>
</xs:simpleType>
```
must result in these generated types:
```go
type MyType MyBaseType
type MyBaseType int32
```
Previously it generated:
```go
type MyType *MyBaseType  // note the wrong pointer type here
type MyBaseType int32
```
which would generate this type of …

Type definitions stemming from simple types must not be pointer types

---

fixtures/epcis/epcisquery.src
gowsdl.go
traverser.go
types_tmpl.go
xsd.go

This fixes #224.
The problem was initially addressed with PR #109 (issue #73) in commit dd8f1cae4f65c55c7ddca89a21925dd9d85ad14e. However that commit does not address all possible name mismatch scenarios.
If multiple elements with different names are of the same complexType, the existing logic arbitrarily takes the first element's name for the struct's XMLName field tag. All other elements with different names then conflict with that tag.
Errors would typically look like these:
- `"xml: name \"order\" in tag of example.AckType.Order conflicts with name \"orderType\" in *example.OrderType.XMLName"`
- `"expected element type <historyType> but have <history>"`
This PR proposes two changes:
1. A modification to the original commit dd8f1cae4f65c55c7ddca89a21925dd9d85ad14e to avoid generating …

Avoid XML name conflicts in XML tags between field tag and struct's XMLName field

---

fixtures/chromedata.wsdl
gowsdl.go
gowsdl_test.go

This PR fixes #236 
In short, this XML:
```xml
<simpleType name="DriveTrain">
<restriction base="string">
<enumeration value="" />
<enumeration value="Front Wheel Drive" />
<enumeration value="Rear Wheel Drive" />
<enumeration value="All Wheel Drive" />
<enumeration value="Four Wheel Drive" />
</restriction>
</simpleType>
```
Will generate the following broken go code:
This PR changes the implementation so it is generated like so:

Handle empty strings in enums

---

README.md

* Updated the README with Install instructions for Go version 1.20.
* Removed the word "binary" from the "Download binary releases" link, since there are no binaries.

Updated Install Instructions

---

soap/soap.go

HI,
using headers in SOAP will result in XML elements like:
---
<soap:Header>
<Headers>
...
---
which is not valid.
This PR will fix this issue
Thanks,
Kristian

adjust SOAP Header handling to not include headers/header elements

---

gowsdl.go

I am having the following enumeration
```xml
<xs:simpleType name="UebertragungsverfahrenType">
<xs:restriction base="xs:string">
<xs:enumeration value="ADSL2AM"/>
<xs:enumeration value="ADSL2+AM"/>
</xs:restriction>
</xs:simpleType>
```
Currently `normalize` just throws array all illegal characters in an identifier, leading to a duplicate const value and a compilation error.
This PR introduces a specialCharacterMapping, which adds a `Plus` for the `+` in the name

Enumeration duplicates with special characters like "+"

---

soap/MTOMEncoder.go

Makes more MTOM-based services work correctly. Sometimes, some services do not use the exact names in their headers.

Less restrictive checks in MTOMDecoder

---

soap/soap.go

I encountered the same issue as emc in issue #258. Please revert the PR from issue #250.
This reverts commit f6c12a7e7555c1305af484011d9e72bda84dd30b.

Revert "adjust SOAP Header handling to not include headers/header elements"
